AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template with 1 Auto Scaling Group and 3 EC2 instances running Apache.

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
  VPCName:
    Type: String
    Default: vpc-0b3c34c4ea9640f9e
    Description: VPC Name
  SubnetName:
    Type: String
    Default: subnet-0202bcf8ba232706c
    Description: Subnet Name

Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      VpcId: !Ref VPCName  # If you're not using a custom VPC, remove this line
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: apache-launch-template
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !Ref WebServerSecurityGroup
        ImageId: ami-0f5d1713c9af4fe30
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Welcome to Apache on EC2 in ASG!</h1>" > /var/www/html/index.html

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref SubnetName
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '3'
      MaxSize: '3'
      DesiredCapacity: '3'
      TargetGroupARNs: []  # Optional: if you're attaching to ALB

Outputs:
  ASGName:
    Description: Name of the Auto Scaling Group
    Value: !Ref AutoScalingGroup
