---
- name: Deploy CloudFormation stack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Launch CloudFormation stack
      cloudformation:
        stack_name: ansible-cloudformation-asg-alb-tg2
        state: present
        template: cloudformation-asg-alb-tg.yml
        region: ap-southeast-2
        capabilities:
          - CAPABILITY_NAMED_IAM
      register: stack_output

    - name: Print CloudFormation output
      debug:
        var: stack_output
