---
- name: Deploy CloudFormation stack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Launch CloudFormation stack
      cloudformation:
        stack_name: ansible-cloudformation-asg-alb-tg-deploygit
        state: present
        template_body: "{{ lookup('file', '../CloudformationTemplate/cloudformation-asg-alb-tg-deploygit.yml') }}"
        region: ap-southeast-2
        capabilities:
          - CAPABILITY_NAMED_IAM
      register: stack_output

    - name: Print CloudFormation output
      debug:
        var: stack_output
